### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by ismaileke** [bariscodefxy/PHP-Life#1]
** Call to undefined function PHPLife\glfwInit() in C:\Users\user\Downloads\PHP-Life-master\src\Launcher.php:25**
![image](https://github.com/bariscodefxy/PHP-Life/assets/74091824/ae2dbe35-8896-4086-b6c6-cdf9af8b6671)

**Comment by bariscodefxy** [comment]
You must compile or install [PHP-GLFW](https://github.com/mario-deluna/php-glfw) .
